cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED CHECK_ROOT)
    message(FATAL_ERROR "Set CHECK_ROOT to a temporary directory")
endif()
get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(CURRENT_PORT_DIR "${REPOSITORY_ROOT}/overlay-ports/memkind")
set(CURRENT_PACKAGES_DIR "${CHECK_ROOT}/packages")
set(CURRENT_INSTALLED_DIR "${CHECK_ROOT}/installed")
set(CURRENT_BUILDTREES_DIR "${CHECK_ROOT}/buildtrees")
set(FEATURES core)
file(READ "${CURRENT_PORT_DIR}/vcpkg.json" manifest)
string(JSON VERSION GET "${manifest}" version)

function(vcpkg_from_github)
    cmake_parse_arguments(PARSE_ARGV 0 arg "" "OUT_SOURCE_PATH;REPO;REF;SHA512;HEAD_REF" "PATCHES")
    file(MAKE_DIRECTORY "${CHECK_ROOT}/source")
    set(archive "${CHECK_ROOT}/source.tar.gz")
    file(DOWNLOAD "https://github.com/${arg_REPO}/archive/${arg_REF}.tar.gz" "${archive}"
        EXPECTED_HASH "SHA512=${arg_SHA512}" STATUS status TLS_VERIFY ON)
    list(GET status 0 code)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Download failed: ${status}")
    endif()
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${CHECK_ROOT}/source")
    set(source "${CHECK_ROOT}/source/memkind-${VERSION}")
    foreach(patch IN LISTS arg_PATCHES)
        execute_process(COMMAND git apply --check "${CURRENT_PORT_DIR}/${patch}"
            WORKING_DIRECTORY "${source}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Patch ${patch} does not apply in the production order")
        endif()
        execute_process(COMMAND git apply "${CURRENT_PORT_DIR}/${patch}"
            WORKING_DIRECTORY "${source}" RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Patch ${patch} could not be applied")
        endif()
    endforeach()
    message(STATUS "All production patches applied in order with the pinned archive checksum")
    set("${arg_OUT_SOURCE_PATH}" "${source}" PARENT_SCOPE)
endfunction()

function(vcpkg_make_configure)
    cmake_parse_arguments(PARSE_ARGV 0 arg "COPY_SOURCE;AUTORECONF" "SOURCE_PATH" "OPTIONS")
    execute_process(COMMAND autoreconf --force --install --verbose
        WORKING_DIRECTORY "${arg_SOURCE_PATH}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Autotools regeneration failed: ${result}")
    endif()
    execute_process(COMMAND bash -n "${arg_SOURCE_PATH}/configure" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generated configure is not valid shell")
    endif()
    file(WRITE "${CHECK_ROOT}/source-path.txt" "${arg_SOURCE_PATH}\n")
endfunction()
function(vcpkg_make_install)
endfunction()
function(vcpkg_fixup_pkgconfig)
endfunction()
function(vcpkg_install_copyright)
endfunction()

include("${CURRENT_PORT_DIR}/portfile.cmake")
message(STATUS "Production patch chain and generated configure syntax validated")
